### ISSUE TITLE
Can't run the demo

### ISSUE THREAD

**Issue by GraphicsHunter** [seanlaff/simple-streaming-datasource#7]
Hi,

I'm trying to visualize the data output from `server.go` by using the template dashboard provided in demodashboard.json, but I get no visualization:
![image](https://user-images.githubusercontent.com/35640495/53833205-48bda100-3f88-11e9-9184-f392cd0ddf67.png)

With the following settings:
![image](https://user-images.githubusercontent.com/35640495/53833236-5541f980-3f88-11e9-9f01-f2f162b407b9.png)

This is how I set up the data source:

![image](https://user-images.githubusercontent.com/35640495/53833042-f3818f80-3f87-11e9-9f39-fac89f2067b5.png)

Any idea why I'm not getting any visualizations on the panels?

Thanks in advance!

**Comment by seanlaff** [comment]
Perhaps it might be the `Access: Browser` setting. Have you tried with `Access: Server`? (I've only tested with `Access: Server` so far). 

What browser/version are you using?

**Comment by GraphicsHunter** [comment]
Thanks for the quick answer, I'm running this on Docker, pulling the Grafana:6.0.0 image. I also tried with `Access: Server`, but it didn't work. I am running this on Google Chrome.

**Comment by seanlaff** [comment]
Ah I see. I've been running this in grafana 5.x.

I can take a look later today to investigate any potential 6.x incompatibility

**Comment by seanlaff** [comment]
Things seem to be working fine for me in 6.0.0 (built from source). I'll try the official 6.0.0 docker image next
<img width="781" alt="screen shot 2019-03-05 at 5 55 21 pm" src="https://user-images.githubusercontent.com/3194832/53843386-359ed700-3f70-11e9-9703-36a225c57bab.png">

**Comment by GraphicsHunter** [comment]
Interesting. I am running `go run server.go` outside the container(i.e. on the host machine), it might be due to that. I'll try to run the script from inside the container and see if that's the reason why.

**Comment by seanlaff** [comment]
Ah yeah, that'd be it. If you're using docker on mac I think you could do `http://docker.for.mac.localhost:8080` to get to the running go server thats on your host machine.

**Comment by GraphicsHunter** [comment]
It worked, thank you! Is it the same case for Linux machines too? I also had the same problem there.

**Comment by seanlaff** [comment]
Running the container in docker with `--net=host` should do the trick for ya 👍
