### ISSUE TITLE
Installing help needed

### ISSUE THREAD

**Issue by MarkoBursic** [seanlaff/simple-streaming-datasource#9]
`Install as you would any grafana datasource. `

I did 👍 
`cd /var/lib/grafana/ plugins`

`git clone https://github.com/seanlaff/simple-streaming-datasource.git`

 `service  grafana-server restart`

Got a new datasource : simple-streaming-datasource

Made a new dashboard and copied JSON script in the import window. Dashboard sets up.
I have add a new datasource instance of Simple Streaming Datasource.
configured as http://localhost:8080
Access: tried both browser and server, with skip TLS verfify,...and many other options

I did `go run server.go ` . In the web browser I can see data being steamed, but query inspector does not show any data nor the panel is moving.

**Comment by seanlaff** [comment]
Hey @MarkoBursic , thanks for your interest. The workarounds employed in this repo are no longer supported in the newer versions of grafana- however, streaming is now an officially support feature! That being said, you may still find some of the code in here useful (splitting newline-delimiited streams of json, etc). I'm going to add the following note to the readme to prevent confusion in the future. 

> As of Grafana v6.4, the hacks in this repo are no longer supported/necessary. Grafana v6.4 added native streaming support after positive community feedback. Please refer the offical streaming examples in the [testdata-datasource](https://github.com/grafana/grafana/tree/master/public/app/plugins/datasource/testdata) or alternatively, the [loki-datasource](https://github.com/grafana/grafana/tree/master/public/app/plugins/datasource/loki).

**Comment by MarkoBursic** [comment]
Thank you for the reply. As for testdata-datasource, I have checked, it just work on its own. No client is implemented as it streams random data and it doesn't seem to be able to use any external data streaming. Loki seems to complicated for this simple task, I don't even understand what Loki is, lots of clouds everywhere but no simple and straightforward solution.
